version: "3"

services:
  exchange-rate-backend-service:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - APP_COMPONENT=${APP_COMPONENT}
      - DB_MAX_POOL_SIZE=2
      - DB_MIN_POOL_SIZE=1
      - DB_NAME=exchange_rate_dev
      - DB_SSL=prefer
      - CONNECTION_RETRIES=5
      - READ_DB_HOST=postgres
      - READ_DB_PASS=password
      - READ_DB_PORT=5432
      - READ_DB_USER=postgres
      - WRITE_DB_HOST=postgres
      - WRITE_DB_PASS=password
      - WRITE_DB_PORT=5432
      - WRITE_DB_USER=postgres
      - KAFKA_SERVER=kafka:29092
      - REDIS_DSN=redis://redis:6379

    env_file:
      - .env
    volumes:
      - ./mount:/srv/root
    ports:
      - 5000:5000
    links:
      - postgres
      - kafka
      - redis

    depends_on:
      - postgres
      - kafka
      - redis

  exchangerate-poller:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - APP_COMPONENT=exchangerate-poller
      - DB_MAX_POOL_SIZE=2
      - DB_MIN_POOL_SIZE=1
      - DB_NAME=exchange_rate_dev
      - DB_SSL=prefer
      - CONNECTION_RETRIES=5
      - READ_DB_HOST=postgres
      - READ_DB_PASS=password
      - READ_DB_PORT=5432
      - READ_DB_USER=postgres
      - WRITE_DB_HOST=postgres
      - WRITE_DB_PASS=password
      - WRITE_DB_PORT=5432
      - WRITE_DB_USER=postgres
      - KAFKA_SERVER=kafka:29092
      - REDIS_DSN=redis://redis:6379

    env_file:
      - .env
    volumes:
      - ./mount:/srv/root
    ports:
      - 5001:5001
    links:
      - postgres
      - kafka
      - redis

    depends_on:
      - postgres
      - kafka
      - redis

  exchangerate-processor:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - APP_COMPONENT=exchangerate-processor
      - DB_MAX_POOL_SIZE=2
      - DB_MIN_POOL_SIZE=1
      - DB_NAME=exchange_rate_dev
      - DB_SSL=prefer
      - CONNECTION_RETRIES=5
      - READ_DB_HOST=postgres
      - READ_DB_PASS=password
      - READ_DB_PORT=5432
      - READ_DB_USER=postgres
      - WRITE_DB_HOST=postgres
      - WRITE_DB_PASS=password
      - WRITE_DB_PORT=5432
      - WRITE_DB_USER=postgres
      - KAFKA_SERVER=kafka:29092
      - REDIS_DSN=redis://redis:6379

    env_file:
      - .env
    volumes:
      - ./mount:/srv/root
    ports:
      - 5002:5002
    links:
      - postgres
      - kafka
      - redis

    depends_on:
      - postgres
      - kafka
      - redis

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./mount:/srv/root
    ports:
      - 5321:5432

  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "32181:32181"
    volumes:
      - ./zookeeper-data/zk-data:/var/lib/zookeeper/data
      - ./zookeeper-data/zk-txn-logs:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    links:
      - zookeeper
    extra_hosts:
      - "kafka:127.0.0.1"
    ports:
      - "29092:29092"
    volumes:
      - ./kafka-data/:/var/lib/kafka/data

networks:
  default:
    driver: bridge
